// ecosystem-ci/fixtures/controlled/vue-vite/css/src/App.vue
<template>
  <article class="card" data-probe="card" data-identity="card">Card</article>
  <button class="action" data-identity="action">Toggle details</button>
  <section class="responsive" data-probe="responsive-layout" data-identity="responsive">Responsive</section>
</template>
<style scoped>
.card {
  padding: 13px;
  color: rgb(20, 30, 40);
}
.card:hover {
  background-color: rgb(210, 220, 230);
}
.action:focus {
  outline: 2px solid rgb(30, 90, 150);
}
.action:focus-visible {
  outline-offset: 3px;
}
.responsive {
  width: 100px;
}
@media (min-width: 700px) {
  .responsive {
    width: 200px;
  }
}
.retained {
  display: block;
}
</style>

// ecosystem-ci/fixtures/controlled/next/sass/app/page.jsx
import styles from './page.module.sass';

export default function Page() {
  return <main>
    <article className={styles.card} data-probe="card" data-identity="card">Card</article>
    <button className={styles.action} data-identity="action">Toggle details</button>
    <section className={styles.responsive} data-probe="responsive-layout" data-identity="responsive">Responsive</section>
  </main>;
}
